## AI기반 챗봇 및 OCR 개발 전문가 과정

### 교과목명 : 딥러닝
- 평가일 : 24. 2. 14
- 성명 :
- 점수 :

Q1. MNIST 데이터셋에 대하여 tensorflow/keras Sequential 모델을 사용하여 아래와 같이 완전 연결 신경망(Feedforward Neural Network)을 구성한 후 모델링 및 평가를 수행하세요.
- 입력 형태(input_shape): input_shape=(28, 28)로 설정. 이는 모델이 28x28 픽셀 크기의 이미지를 입력으로 받는다는 것을 의미이며 첫 번째 레이어인 Flatten은 이 2D 이미지를 784(28x28) 요소의 1D 배열로 평탄화.Flatten(input_shape=(28, 28))

- 레이어 구성: 모델은 평탄화 레이어(Flatten) 다음에 128개의 뉴런을 가진 완전 연결 레이어(Dense)를 가지고 있으며, 그 다음에는 10개의 출력 뉴런을 가진 또 다른 Dense 레이어가 있다. 출력 레이어는 소프트맥스 활성화 함수를 사용하여 다중 클래스 분류를 수행.

- 컴파일:
  - optimizer='adam',
  - loss='sparse_categorical_crossentropy',
  - metrics=['accuracy']

- epochs=5


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense

# MNIST 데이터셋 로드
mnist = tf.keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(train_images, train_labels, epochs=5)
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_loss)
print(test_acc)







Epoch 1/5
1875/1875 [==============================] - 9s 3ms/step - loss: 12.8356 - accuracy: 0.0970
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 2.3118 - accuracy: 0.0987
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 2.3039 - accuracy: 0.0987
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 2.3026 - accuracy: 0.0987
Epoch 5/5
313/313 [==============================] - 1s 3ms/step - loss: 2.3026 - accuracy: 0.0980
2.30259108543396
0.09799999743700027


In [ ]:
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy']
)

model.fit(train_images, train_labels, epochs=5)
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 2.6260 - accuracy: 0.8646
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.4007 - accuracy: 0.9086
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2901 - accuracy: 0.9282
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2341 - accuracy: 0.9395
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.3227 - accuracy: 0.9322
0.932200014591217


Q2. MNIST 데이터셋에 대하여 함수형 API를 사용하여 같은 아래사항을 준수하여  모델 학습 및 평가를 수행하세요.
- 데이터 정규화 (0과 1 사이의 값으로 스케일링)
- 입력 데이터의 차원을 (28, 28)에서 모델에 적합한 형태로 조정
- 레이어 연결(hidden 2개, 출력 1개)
- 모델 생성
- 모델 컴파일 : optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy']
- 모델 학습 : epochs=5, batch_size=32, validation_split=0.2
- 모델 평가

In [ ]:
from tensorflow.keras.layers import Input, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.datasets import mnist

# MNIST 데이터셋 로드
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [ ]:
train_images = train_images / 255.0
test_images = test_images / 255.0

input_layer = Input(shape=(28, 28))
x = Flatten()(input_layer)

hidden1 = Dense(128, activation='relu')(x)
hidden2 = Dense(64, activation='relu')(hidden1)
output_layer = Dense(10, activation='softmax')(hidden2)

model = Model(inputs=input_layer, outputs=output_layer)

model.compile(
    optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy']
)
model.fit(train_images, train_labels, epochs=5, batch_size=32, validation_split=0.2)
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)
print(test_loss)

Epoch 1/5
1500/1500 [==============================] - 7s 4ms/step - loss: 0.2600 - accuracy: 0.9236 - val_loss: 0.1257 - val_accuracy: 0.9644
Epoch 2/5
1500/1500 [==============================] - 8s 5ms/step - loss: 0.1115 - accuracy: 0.9663 - val_loss: 0.1104 - val_accuracy: 0.9672
Epoch 3/5
1500/1500 [==============================] - 10s 7ms/step - loss: 0.0782 - accuracy: 0.9759 - val_loss: 0.1046 - val_accuracy: 0.9706
Epoch 4/5
1500/1500 [==============================] - 7s 5ms/step - loss: 0.0573 - accuracy: 0.9821 - val_loss: 0.0961 - val_accuracy: 0.9718
Epoch 5/5
313/313 [==============================] - 1s 3ms/step - loss: 0.0784 - accuracy: 0.9758
0.9757999777793884
0.07838941365480423


Q3. 주어진 텍스트 데이터셋을 토큰화하고, 다음 사항을 수행하세요.

데이터셋:

"I love machine learning."<br>
"I love coding in Python."<br>
"Machine learning can be fun."

- 각 단어에 고유한 정수 인덱스를 할당하고 각 문장을 정수 시퀀스로 변환하세요.


In [ ]:
from keras.preprocessing.text import Tokenizer

texts = ['I love machine learning', 'I love coding in Python', 'Machine learning can be fun']

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
print(tokenizer.word_index)
print(tokenizer.texts_to_sequences(texts))

{'i': 1, 'love': 2, 'machine': 3, 'learning': 4, 'coding': 5, 'in': 6, 'python': 7, 'can': 8, 'be': 9, 'fun': 10}
[[1, 2, 3, 4], [1, 2, 5, 6, 7], [3, 4, 8, 9, 10]]


Q4. Q3에서 생성한 정수 시퀀스에 패딩을 추가하여 모든 시퀀스의 길이를 동일하게 만드세요.

In [ ]:
from keras.preprocessing.sequence import pad_sequences

In [ ]:
texts = ['I love machine learning', 'I love coding in Python', 'Machine learning can be fun']
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
seq = tokenizer.texts_to_sequences(texts)
print(seq)
seq = pad_sequences(seq, padding='post')
print(seq)

word_size = len(tokenizer.word_index) + 1
print(to_categorical(seq, num_classes=word_size))

[[1, 2, 3, 4], [1, 2, 5, 6, 7], [3, 4, 8, 9, 10]]
[[ 1  2  3  4  0]
 [ 1  2  5  6  7]
 [ 3  4  8  9 10]]
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]]


Q5. 주어진 텍스트 데이터셋에 대해 원-핫 인코딩을 수행하세요. (사용할 최대 단어 수 설정 : num_words=1000)

In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical

# 데이터셋 정의
texts = [ "I love coding in Python.","I love machine learning.", "Machine learning can be fun."]

In [ ]:
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(texts)
print(tokenizer.texts_to_matrix(texts, mode='binary'))

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
