## AI기반 챗봇 및 OCR 개발 전문가 과정

### 교과목명 : 넘파이, 시각화, 통계
- 평가일 : 24.1.22
- 성명 : 한정현
- 점수 :

In [39]:
# 드라이브 연동
import google.drive from content

SyntaxError: invalid syntax (<ipython-input-39-37428a817ce9>, line 1)

Q1. array2d에서 슬라이싱을 사용해서 아래와 같이 출력하세요.

array2d = np.arange(1,10).reshape(3,3)

In [ ]:
[[1 2 3]
[4 5 6]
[7 8 9]]

[[2 3]
[5 6]]

[1 4]

In [16]:
# Q1 솔루션
import numpy as np
array2d = np.arange(1,10).reshape(3,3)
# print(array2d)

print(array2d[:,:],'\n')
print(array2d[0:2, 1:3],'\n')
print(array2d[0:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]] 

[1 4]


Q2. 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)

In [19]:
# Q2 솔루션
import numpy as np
ar100 = np.arange(1,101)

sol1 = ar100[(ar100 % 5 == 0) & (ar100 % 2 == 0)]
print(sol1)

for i in range(1,101):
  if (i % 5 == 0 ) and (i % 2 == 0 ) :
    print(i)

[ 10  20  30  40  50  60  70  80  90 100]
10
20
30
40
50
60
70
80
90
100


Q3. 주가데이터.csv를 불러와서 다음을 수행하세요.
- 아래 df에서 Close 칼럼을 Box Plot으로 표현하세요
- df Close 칼럼의 값에서 이상치로 의심할 수 있는 관측치를 출력하세요.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/kdt_231026/m3_분석라이브러리/visualization/dataset/주가데이터.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/kdt_231026/m3_분석라이브러리/visualization/dataset/주가데이터.csv'

In [ ]:
df.plt(kind=box)


Q4. fish_multi A, B 그룹에 이상치를 10, 2를 추가한 후 Box Plot을 그리고 이상치를 구하세요.


In [ ]:
import pandas as pd
fish_multi = pd.read_csv('/content/drive/MyDrive/kdt_231026/m3_분석라이브러리/visualization/dataset/4_fm2.csv')
fish_multi.head()

species  length
0       A       2
1       A       3
2       A       3
3       A       4
4       A       4

Q5. 적절한 데이터를 생성하여 선그래프, 히스토그램, 산점도, 막대그래프 4개의 subplot으로 구성된 2 x 2 그래프를 작성하세요.

In [ ]:
import matplotlib.pyplot as plt
plt.subplot(0,1,)

Q6. 정규 분포를 따르는 아래 데이터를 생성한 후 과제를 수행하세요.

data = stats.norm.rvs(loc=172.5, scale=6, size=10000)

- 생성된 데이터를 사용하여 히스토그램 작성
- 히스토그램의 빈(bin) 수를 조정해서 작성
- 두개의 그래프를 1행 2열로 표현

Q7. 주어진 숫자 배열(예: [4, 8, 15, 16, 23, 42])에 대해 평균과 중앙값을 계산한 후 배열에 두 개의 극단값을 추가한 후(예: -100, 100), 다시 평균과 중앙값을 계산하고 비교하세요.

In [40]:
ar = [4, 8, 15, 16, 23, 42]
np.mean(ar)
np.

SyntaxError: invalid syntax (<ipython-input-40-599a09469269>, line 3)

Q8. 아래 두개의 데이터로 공분산(covariance)과 상관계수를 계산하세요.
- data1 = [65, 72, 78, 65, 72, 70, 65, 68]
- data2 = [72, 69, 74, 66, 70, 75, 65, 72]

In [54]:
data1 = [65, 72, 78, 65, 72, 70, 65, 68]
data2 = [72, 69, 74, 66, 70, 75, 65, 72]
print(np.cov(data1)[0,1])
print(np.coef(data2)[0,1])

IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

Q9. 주어진 데이터 배열의 사분위수(제1사분위수, 중앙값, 제3사분위수)를 계산한 후 데이터의 10번째 백분위수와 90번째 백분위수를 계산하여 출력하세요.
- data = np.arange(1000)

In [36]:
# Q9. 솔루션
data = np.arange(1000)
# p1 = np.percentile.data(25)
p1 = np.percentile(data[0,25])


TypeError: _percentile_dispatcher() missing 1 required positional argument: 'q'

Q10. Z-점수 정규화를 사용하여 주어진 데이터 배열을 표준화하세요.(평균이 0이고 분산이 1이 되도록 특성의 크기를 조정)
- data = np.array([[1], [2], [3], [4], [5]])

In [37]:
# Q10. 솔루션
data = np.array([[1], [2], [3], [4], [5]])


TypeError: 'numpy.ndarray' object is not callable