In [ ]:
#### 판다스


* DataFrame과 Series: 2차원 테이블과 1차원 배열(하나의 칼럼) 형태의 데이터 구조를 제공
* 데이터 처리: 데이터 정제, 필터링, 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

Series 기본 구조
- Series는 값의 리스트를 담고 있으며, 각 값은 고유한 인덱스와 연결되어 있다.
- 기본적으로, 이 인덱스는 0부터 시작하는 정수지만, 문자열 또는 날짜와 같은 다른 타입으로 지정할 수도 있다.
- Series는 다양한 데이터 타입을 저장할 수 있다. 예를 들어, 정수, 실수, 문자열, 파이썬 객체 등이 포함된다.
- 강력한 인덱싱 및 슬라이싱 기능을 제공. 특정 인덱스의 값에 접근하거나, 특정 조건을 만족하는 데이터만을 필터링할 수 있다.
- Series를 다른 형태의 데이터 구조로 변환하는 것이 간단하다. 예를 들어, Series를 리스트, 딕셔너리, 혹은 DataFrame으로 변환할 수 있다.

In [133]:
#시리즈 클래스 만들기
#pandas 불러오기 (pd)
import pandas as pd # pandas 를 pd 로 줄여서 부르겠다. as(alias)

# k:v 구조(키 밸류 구조-딕셔너리)를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1, 'b':2, 'c':3}
sr = pd.Series(dict_data) # sr 객체에 pd. 하고 Series 사용. 그함수안에 dict_data 대입
print(sr) # a b c  가 인덱스..
print(sr+10)
type(sr)

TypeError: 'str' object is not callable

In [134]:
# 리스트를 시리즈로 변환
list_data = ['2019-07-02',3.14,'ABC',100,True]
sr = pd.Series(list_data)
print(sr) # 별도로 인덱스를 안넣으면 0~ 숫자 인덱스가 기입됨
type(sr)

TypeError: 'str' object is not callable

In [127]:
list('abcde')

['a', 'b', 'c', 'd', 'e']

In [135]:
# 리스트를 시리즈로 변환
# 숫자 말고 문자 인덱스로 하기
list_data = ['2019-07-02',3.14,'ABC',100,True]
sr = pd.Series(list_data, index=list('abcde')) # 인덱스에 문자 기입
print(sr)
type(sr)

TypeError: 'str' object is not callable

In [136]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

TypeError: 'str' object is not callable

In [137]:
# 튜플을 시리즈로 변환
import pandas as pd
tup_data = ('kevin','2019-07-02','남',True)
sr = pd.Series(tup_data, index=['Name', 'Date', 'Gender', 'Teacher'])
print(sr)
type(sr)

TypeError: 'str' object is not callable

In [58]:
#인덱싱
import warnings
warnings.filterwarnings('ignore')
print(sr[0], type(sr))
print(sr['Name'])

kevin <class 'pandas.core.series.Series'>
kevin


In [138]:
# data와 gender뽑기
print(sr[[1,2]]) # sr[[1,2]]는 판다스의 팬시 인덱싱을 사용해 여러 인덱스를 한 번에 선택할 수 있다.
# print(sr[1,2]) # 대괄호가 하나면 에러발생시킴.
#sr[1,2]는 튜플 (1,2)를 인덱스로 사용하려고 시도하는 반면 Series 객체는 단일 차원의 인덱스만을 지원

TypeError: 'str' object is not callable

In [14]:
# numpy를 사용해서 배열을 만듦
import numpy as np
s1 = np.arange(11,21,2)
print(s1,type(s1))
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>
a    11
b    13
c    15
d    17
e    19
dtype: int32 <class 'pandas.core.series.Series'>


#### 과제1_1121 : 배열을 생성 후 시리즈로 변환하여 아래와 같이 출력하세요.

In [15]:
# 과제1_1121 솔루션
import numpy as np
import pandas as pd

s1 = np.arange(1000,5000,1000)
# print(s1)
s2 = pd.Series(s1, index=['Califonia','Ohio','Oregon','Texas'])
print(s2)

Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
dtype: int32


In [17]:
# 과제1_1121 솔루션
import numpy as np
import pandas as pd

list1 = np.arange(1000,5000,1000)
sr = pd.Series(list1, index= ['Califonia','Ohio','Oregon','Texas'])
sr.name = 'population'
sr.index.name = 'state'
print(sr)

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32


In [40]:
# Series -> list sr.tolist()
sr_tolist = sr.tolist()
print(sr_tolist,type(sr_tolist))

[nan, 2000.0, 3000.0, 4000.0] <class 'list'>


In [19]:
# Series -> dic dict sr.to_dict()
sr_todic = sr.to_dict()
sr_todic

{'Califonia': 1000, 'Ohio': 2000, 'Oregon': 3000, 'Texas': 4000}

In [39]:
sr_df = sr.to_frame(name='Value')
print(sr_df,type(sr_df))

            Value
state            
Califonia     NaN
Ohio       2000.0
Oregon     3000.0
Texas      4000.0 <class 'pandas.core.frame.DataFrame'>


In [23]:
# Null 값 처리..
# 일부러 Null값을 넣어보고 처리해보자
sr.Califonia = np.nan # (np.nan 으로 널값만들기)
sr

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [33]:
# Null 여부를 확인하는 방법
null_sr = sr.isnull()
null_sr

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [36]:
# null이 몇개인지보려면 이렇게 하면됨
null_sr.sum() # True인것만 개수를 셈.  

1

In [37]:
not_null_sr = sr.notnull()
not_null_sr

state
Califonia    False
Ohio          True
Oregon        True
Texas         True
Name: population, dtype: bool

In [41]:
# null 값을 특정한 숫자로 채우는 것
filled_sr = sr.fillna(0) # na를 채워라 0으로,,
filled_sr

state
Califonia       0.0
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [42]:
sr # sr은 여전히 null값이있음

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [43]:
# sr 의 null값 삭제
dropped_sr = sr.dropna() # sr.dropna()를 사용
dropped_sr

state
Ohio      2000.0
Oregon    3000.0
Texas     4000.0
Name: population, dtype: float64

In [45]:
# 널깂들 갯수 확인. 다 처리가 되었는지 확인
dropped_sr.isnull().sum()

0

#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체. 
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 데이터프레임 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [56]:
# 배열을 데이터프레임(2차원)으로 변환
import numpy as np
import pandas as pd
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3)) # 3행 3열.짜리의 배열. 100에서 120사이

df = pd.DataFrame(data, index=['d1','d2','d3'], columns = ['pd','sales','inv'])
# df = pd.DataFrame(data) # 이렇게 하면 그냥 0 1 2 0 1 2
# 만든배열data 가 들어가고, 행들에 인덱스 d1 d2 d3, 속성들에 pd sales inv
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [ ]:
# pandas indexing : iloc 정수 인덱스, loc 이름 인덱스
print(df.iloc[1]) # iloc 인덱스 1. 슬라이싱 생략가능 행, 열 순임
# 현재 이름 인덱스지만 정수 인덱스로 뽑아줄 수 있음

In [69]:
# pandas indexing : iloc 정수 인덱스, loc 이름 인덱스
print(df.iloc[1,:]) # iloc 인덱스 1.
# 현재 이름 인덱스지만 정수 인덱스로 뽑아줄 수 있음

sales    103
inv      107
Name: d2, dtype: int32


In [70]:
print(df.loc['d2',:]) # loc 인덱스 'd2' (이름인덱스)
# iloc[1] = loc['d2']

pd       103
sales    103
inv      107
Name: d2, dtype: int32


In [88]:
# 107만출력
print(df.iloc[1,2])

print(df.loc['d2','inv'])

107
107


In [87]:
df.loc['d3']=0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [159]:
# 2차원 리스트를 데이터프레임으로 변환
a = np.random.randint(1,5,size=(10,5))
list1 = a.tolist()
list1

[[3, 3, 2, 4, 3],
 [4, 1, 1, 1, 3],
 [2, 1, 1, 4, 3],
 [3, 4, 3, 4, 2],
 [4, 2, 3, 1, 3],
 [1, 3, 4, 4, 2],
 [4, 1, 4, 2, 1],
 [1, 3, 1, 4, 3],
 [2, 3, 2, 2, 3],
 [1, 4, 2, 1, 2]]

In [180]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame(list1,columns=['c1','c2','c3','c4','c5'])
df1
# df1.head(3) # 앞에서 3개
# df1.tail() # 뒤에서 뽑기 기본값 5개

c1  c2  c3  c4  c5
0   3   3   2   4   3
1   4   1   1   1   3
2   2   1   1   4   3
3   3   4   3   4   2
4   4   2   3   1   3
5   1   3   4   4   2
6   4   1   4   2   1
7   1   3   1   4   3
8   2   3   2   2   3
9   1   4   2   1   2

In [207]:
# 데이터프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values # 배열
print(ar, type(ar))
print()
li=ar.tolist() #리스트
print(li,type(li))
print()

# 이렇게 하면 키 밸류 가 키 c1 인데 밸류가 {0:3, ~} 이런식으로 딕셔너리안에 딕셔너리로 되는데.. 이러면 안되니까 밸류를 리스트화시켜야함
dict = df1.to_dict() 
print(dict,type(dict))
#{'c1': {0: 3, 1: 4, 2: 2, 3: 3, 4: 4, 5: 1, 6: 4, 7: 1, 8: 2, 9: 1}, 'c2': {0: 3, 1: 1, 2: 1, 3: 4, 4: 2, 5: 3, 6: 1, 7: 3, 8: 3, 9: 4}, 'c3': {0: 2, 1: 1, 2: 1, 3: 3, 4: 3, 5: 4, 6: 4, 7: 1, 8: 2, 9: 2}, 'c4': {0: 4, 1: 1, 2: 4, 3: 4, 4: 1, 5: 4, 6: 2, 7: 4, 8: 2, 9: 1}, 'c5': {0: 3, 1: 3, 2: 3, 3: 2, 4: 3, 5: 2, 6: 1, 7: 3, 8: 3, 9: 2}} <class 'dict'>

# dict = df1.to_dict('list') 이런식으로 따옴표 리스트로 컬럼의 값들이 여러개일때 키 str : 밸류[] 이렇게 하면 됨
print()
dict = df1.to_dict('list')
print(dict,type(dict))
#{'c1': [3, 4, 2, 3, 4, 1, 4, 1, 2, 1], 'c2': [3, 1, 1, 4, 2, 3, 1, 3, 3, 4], 'c3': [2, 1, 1, 3, 3, 4, 4, 1, 2, 2], 'c4': [4, 1, 4, 4, 1, 4, 2, 4, 2, 1], 'c5': [3, 3, 3, 2, 3, 2, 1, 3, 3, 2]} <class 'dict'> 

[[3 3 2 4 3]
 [4 1 1 1 3]
 [2 1 1 4 3]
 [3 4 3 4 2]
 [4 2 3 1 3]
 [1 3 4 4 2]
 [4 1 4 2 1]
 [1 3 1 4 3]
 [2 3 2 2 3]
 [1 4 2 1 2]] <class 'numpy.ndarray'>

[[3, 3, 2, 4, 3], [4, 1, 1, 1, 3], [2, 1, 1, 4, 3], [3, 4, 3, 4, 2], [4, 2, 3, 1, 3], [1, 3, 4, 4, 2], [4, 1, 4, 2, 1], [1, 3, 1, 4, 3], [2, 3, 2, 2, 3], [1, 4, 2, 1, 2]] <class 'list'>

{'c1': {0: 3, 1: 4, 2: 2, 3: 3, 4: 4, 5: 1, 6: 4, 7: 1, 8: 2, 9: 1}, 'c2': {0: 3, 1: 1, 2: 1, 3: 4, 4: 2, 5: 3, 6: 1, 7: 3, 8: 3, 9: 4}, 'c3': {0: 2, 1: 1, 2: 1, 3: 3, 4: 3, 5: 4, 6: 4, 7: 1, 8: 2, 9: 2}, 'c4': {0: 4, 1: 1, 2: 4, 3: 4, 4: 1, 5: 4, 6: 2, 7: 4, 8: 2, 9: 1}, 'c5': {0: 3, 1: 3, 2: 3, 3: 2, 4: 3, 5: 2, 6: 1, 7: 3, 8: 3, 9: 2}} <class 'dict'>

{'c1': [3, 4, 2, 3, 4, 1, 4, 1, 2, 1], 'c2': [3, 1, 1, 4, 2, 3, 1, 3, 3, 4], 'c3': [2, 1, 1, 3, 3, 4, 4, 1, 2, 2], 'c4': [4, 1, 4, 4, 1, 4, 2, 4, 2, 1], 'c5': [3, 3, 3, 2, 3, 2, 1, 3, 3, 2]} <class 'dict'>


#### 과제2_1121: 5행 5열로 구성된 2차원 배열을 생성하여 데이터프레임으로 변경해서 출력하세요.

In [211]:
# 과제2_1121 솔루션
import pandas as pd
import numpy as np
data_number = np.random.randint(1,11,size=(5,5))
# print(data_number)
dataframe = pd.DataFrame(data_number, index=[1,2,3,4,5], columns=['c1','c2','c3','c4','c5'])
dataframe

c1  c2  c3  c4  c5
1   3   8   9  10   7
2  10   9   6   1   1
3  10   5   7   1  10
4   5   3   3   5   8
5   2  10   7   5   7

#### 과제3_1121: 과제 2번의 데이터프레임을 각각 배열, 리스트, 사전의 형태로 변환하여 출력하세요.

In [226]:
# 과제3_1121 솔루션
by = dataframe.values
print(by)
print()

lst = by.tolist()
print(lst)
print()

sj = dataframe.to_dict('list')
print(sj)

[[ 3  8  9 10  7]
 [10  9  6  1  1]
 [10  5  7  1 10]
 [ 5  3  3  5  8]
 [ 2 10  7  5  7]]

[[3, 8, 9, 10, 7], [10, 9, 6, 1, 1], [10, 5, 7, 1, 10], [5, 3, 3, 5, 8], [2, 10, 7, 5, 7]]

{'c1': [3, 10, 10, 5, 2], 'c2': [8, 9, 5, 3, 10], 'c3': [9, 6, 7, 3, 7], 'c4': [10, 1, 1, 5, 5], 'c5': [7, 1, 10, 8, 7]}


#### 과제4_1121 : 4개의 Series를 결합하여 데이터프레임을 생성하여 출력하세요.
- 출력한 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
- null값을 3개 추가
- null값의 개수를 확인하고 삭제
- 2개의 데이터를 수정
- 1개의 행을 삭제

In [235]:
# 과제4_1121 솔루션
# id, gender, age, region
import pandas as pd
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1,101,size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)
print(i1)

df_1 = pd.concat([i1,g1,a1,r1],axis=1)

0         1
1         2
2         3
3         4
4         5
       ... 
995     996
996     997
997     998
998     999
999    1000
Length: 1000, dtype: int32


In [328]:
print(df_1.iloc[-1])
print()
print(df_1.iloc[-1000,1:1])
print()
print(df_1.iloc[-1000:-2:3])
print()
print(df_1.iloc[123:100000])
print()
print(df_1.iloc[333,3])

0    1000.0
1       1.0
2      31.0
3       1.0
Name: 999, dtype: float64

Series([], Name: 0, dtype: float64)

       0    1     2    3
0    1.0  1.0  81.0  2.0
3    NaN  NaN   NaN  NaN
6    NaN  NaN   NaN  NaN
9    NaN  NaN   NaN  NaN
12   NaN  NaN   NaN  NaN
..   ...  ...   ...  ...
984  NaN  NaN   NaN  NaN
987  NaN  NaN   NaN  NaN
990  NaN  NaN   NaN  NaN
993  NaN  NaN   NaN  NaN
996  NaN  NaN   NaN  NaN

[333 rows x 4 columns]

          0    1     2    3
123     NaN  NaN   NaN  NaN
124     NaN  NaN   NaN  NaN
125     NaN  NaN   NaN  NaN
126     NaN  NaN   NaN  NaN
127     NaN  NaN   NaN  NaN
..      ...  ...   ...  ...
995     NaN  NaN   NaN  NaN
996     NaN  NaN   NaN  NaN
997     NaN  NaN   NaN  NaN
998     NaN  NaN   NaN  NaN
999  1000.0  1.0  31.0  1.0

[877 rows x 4 columns]

nan


In [329]:
df_1.iloc[1,1] = np.nan # (np.nan 으로 널값만들기)
df_1




0    1     2    3
0       1.0  1.0  81.0  2.0
1       NaN  NaN   NaN  NaN
2       3.0  NaN  99.0  5.0
3       NaN  NaN   NaN  NaN
4       NaN  NaN   NaN  NaN
..      ...  ...   ...  ...
995     NaN  NaN   NaN  NaN
996     NaN  NaN   NaN  NaN
997     NaN  NaN   NaN  NaN
998     NaN  NaN   NaN  NaN
999  1000.0  1.0  31.0  1.0

[1000 rows x 4 columns]

In [330]:
dropped_df_1 = df_1.dropna()
dropped_df_1

0    1     2    3
0       1.0  1.0  81.0  2.0
999  1000.0  1.0  31.0  1.0

In [331]:
filled_df_1 = df_1.fillna(123)
filled_df_1

0      1      2      3
0       1.0    1.0   81.0    2.0
1     123.0  123.0  123.0  123.0
2       3.0  123.0   99.0    5.0
3     123.0  123.0  123.0  123.0
4     123.0  123.0  123.0  123.0
..      ...    ...    ...    ...
995   123.0  123.0  123.0  123.0
996   123.0  123.0  123.0  123.0
997   123.0  123.0  123.0  123.0
998   123.0  123.0  123.0  123.0
999  1000.0    1.0   31.0    1.0

[1000 rows x 4 columns]

In [332]:
dropped_df_1.isnull().sum()

0    0
1    0
2    0
3    0
dtype: int64

In [333]:
null_df_1 = df_1.isnull()
null_df_1
null_df_1.sum()

0    997
1    998
2    997
3    997
dtype: int64

In [334]:
not_null_df_1 = df_1.notnull()
not_null_df_1

0      1      2      3
0     True   True   True   True
1    False  False  False  False
2     True  False   True   True
3    False  False  False  False
4    False  False  False  False
..     ...    ...    ...    ...
995  False  False  False  False
996  False  False  False  False
997  False  False  False  False
998  False  False  False  False
999   True   True   True   True

[1000 rows x 4 columns]